
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jan 23 2025 19:34:40 IST (Jan 23 2025 14:04:40 UTC)

// Verification Directory fv/t1c_riscv_cpu 

module t1c_riscv_cpu(clk, reset, Ext_MemWrite, Ext_WriteData,
     Ext_DataAdr, MemWrite, WriteData, DataAdr, ReadData, PC, Result);
  input clk, reset, Ext_MemWrite;
  input [31:0] Ext_WriteData, Ext_DataAdr;
  output MemWrite;
  output [31:0] WriteData, DataAdr, ReadData, PC, Result;
  wire clk, reset, Ext_MemWrite;
  wire [31:0] Ext_WriteData, Ext_DataAdr;
  wire MemWrite;
  wire [31:0] WriteData, DataAdr, ReadData, PC, Result;
  wire [31:0] Instr;
  wire [31:0] DataAdr_rv32;
  wire [31:0] WriteData_rv32;
  wire MemWrite_rv32, n_0, n_1, n_2;
  data_mem datamem(clk, MemWrite, Instr[14:12], DataAdr, WriteData,
       ReadData);
  instr_mem instrmem(PC, Instr);
  riscv_cpu rvcpu(clk, reset, PC, Instr, MemWrite_rv32, DataAdr_rv32,
       WriteData_rv32, ReadData, Result);
  INVXL g659(.A (Ext_MemWrite), .Y (n_2));
  MX2XL g1715__2398(.A (Ext_WriteData[20]), .B (WriteData_rv32[20]),
       .S0 (n_1), .Y (WriteData[20]));
  MX2XL g1716__5107(.A (Ext_WriteData[31]), .B (WriteData_rv32[31]),
       .S0 (n_1), .Y (WriteData[31]));
  MX2XL g1717__6260(.A (Ext_WriteData[28]), .B (WriteData_rv32[28]),
       .S0 (n_1), .Y (WriteData[28]));
  MX2XL g1718__4319(.A (Ext_WriteData[26]), .B (WriteData_rv32[26]),
       .S0 (n_1), .Y (WriteData[26]));
  MX2XL g1719__8428(.A (Ext_WriteData[22]), .B (WriteData_rv32[22]),
       .S0 (n_1), .Y (WriteData[22]));
  MX2XL g1720__5526(.A (Ext_WriteData[7]), .B (WriteData_rv32[7]), .S0
       (n_1), .Y (WriteData[7]));
  MX2XL g1721__6783(.A (Ext_WriteData[13]), .B (WriteData_rv32[13]),
       .S0 (n_1), .Y (WriteData[13]));
  MX2XL g1722__3680(.A (Ext_WriteData[3]), .B (WriteData_rv32[3]), .S0
       (n_1), .Y (WriteData[3]));
  MX2XL g1723__1617(.A (Ext_WriteData[12]), .B (WriteData_rv32[12]),
       .S0 (n_1), .Y (WriteData[12]));
  MX2XL g1724__2802(.A (Ext_WriteData[1]), .B (WriteData_rv32[1]), .S0
       (n_1), .Y (WriteData[1]));
  MX2XL g1725__1705(.A (Ext_WriteData[21]), .B (WriteData_rv32[21]),
       .S0 (n_1), .Y (WriteData[21]));
  MX2XL g1726__5122(.A (Ext_WriteData[8]), .B (WriteData_rv32[8]), .S0
       (n_1), .Y (WriteData[8]));
  MX2XL g1727__8246(.A (Ext_WriteData[11]), .B (WriteData_rv32[11]),
       .S0 (n_1), .Y (WriteData[11]));
  MX2XL g1728__7098(.A (Ext_WriteData[9]), .B (WriteData_rv32[9]), .S0
       (n_1), .Y (WriteData[9]));
  MX2XL g1729__6131(.A (Ext_WriteData[10]), .B (WriteData_rv32[10]),
       .S0 (n_1), .Y (WriteData[10]));
  MX2XL g1730__1881(.A (Ext_WriteData[30]), .B (WriteData_rv32[30]),
       .S0 (n_1), .Y (WriteData[30]));
  MX2XL g1731__5115(.A (Ext_WriteData[14]), .B (WriteData_rv32[14]),
       .S0 (n_1), .Y (WriteData[14]));
  MX2XL g1732__7482(.A (Ext_WriteData[4]), .B (WriteData_rv32[4]), .S0
       (n_1), .Y (WriteData[4]));
  MX2XL g1733__4733(.A (Ext_WriteData[19]), .B (WriteData_rv32[19]),
       .S0 (n_1), .Y (WriteData[19]));
  MX2XL g1734__6161(.A (Ext_WriteData[18]), .B (WriteData_rv32[18]),
       .S0 (n_1), .Y (WriteData[18]));
  MX2XL g1735__9315(.A (Ext_WriteData[29]), .B (WriteData_rv32[29]),
       .S0 (n_1), .Y (WriteData[29]));
  MX2XL g1736__9945(.A (Ext_WriteData[0]), .B (WriteData_rv32[0]), .S0
       (n_1), .Y (WriteData[0]));
  MX2XL g1737__2883(.A (Ext_WriteData[24]), .B (WriteData_rv32[24]),
       .S0 (n_1), .Y (WriteData[24]));
  MX2XL g1738__2346(.A (Ext_WriteData[5]), .B (WriteData_rv32[5]), .S0
       (n_1), .Y (WriteData[5]));
  MX2XL g1739__1666(.A (Ext_WriteData[2]), .B (WriteData_rv32[2]), .S0
       (n_1), .Y (WriteData[2]));
  MX2XL g1740__7410(.A (Ext_WriteData[17]), .B (WriteData_rv32[17]),
       .S0 (n_1), .Y (WriteData[17]));
  MX2XL g1741__6417(.A (Ext_WriteData[16]), .B (WriteData_rv32[16]),
       .S0 (n_1), .Y (WriteData[16]));
  MX2XL g1742__5477(.A (Ext_WriteData[27]), .B (WriteData_rv32[27]),
       .S0 (n_1), .Y (WriteData[27]));
  MX2XL g1743__2398(.A (Ext_WriteData[23]), .B (WriteData_rv32[23]),
       .S0 (n_1), .Y (WriteData[23]));
  MX2XL g1744__5107(.A (Ext_WriteData[6]), .B (WriteData_rv32[6]), .S0
       (n_1), .Y (WriteData[6]));
  MX2XL g1745__6260(.A (Ext_WriteData[15]), .B (WriteData_rv32[15]),
       .S0 (n_1), .Y (WriteData[15]));
  MX2XL g1746__4319(.A (Ext_WriteData[25]), .B (WriteData_rv32[25]),
       .S0 (n_1), .Y (WriteData[25]));
  MX2XL g1747__8428(.A (DataAdr_rv32[19]), .B (Ext_DataAdr[19]), .S0
       (reset), .Y (DataAdr[19]));
  MX2XL g1748__5526(.A (DataAdr_rv32[28]), .B (Ext_DataAdr[28]), .S0
       (reset), .Y (DataAdr[28]));
  MX2XL g1749__6783(.A (DataAdr_rv32[30]), .B (Ext_DataAdr[30]), .S0
       (reset), .Y (DataAdr[30]));
  MX2XL g1750__3680(.A (DataAdr_rv32[7]), .B (Ext_DataAdr[7]), .S0
       (reset), .Y (DataAdr[7]));
  MX2XL g1751__1617(.A (DataAdr_rv32[16]), .B (Ext_DataAdr[16]), .S0
       (reset), .Y (DataAdr[16]));
  MX2XL g1752__2802(.A (DataAdr_rv32[22]), .B (Ext_DataAdr[22]), .S0
       (reset), .Y (DataAdr[22]));
  MX2XL g1753__1705(.A (DataAdr_rv32[8]), .B (Ext_DataAdr[8]), .S0
       (reset), .Y (DataAdr[8]));
  MX2XL g1754__5122(.A (DataAdr_rv32[26]), .B (Ext_DataAdr[26]), .S0
       (reset), .Y (DataAdr[26]));
  MX2XL g1755__8246(.A (DataAdr_rv32[17]), .B (Ext_DataAdr[17]), .S0
       (reset), .Y (DataAdr[17]));
  MX2XL g1756__7098(.A (DataAdr_rv32[9]), .B (Ext_DataAdr[9]), .S0
       (reset), .Y (DataAdr[9]));
  MX2XL g1757__6131(.A (DataAdr_rv32[23]), .B (Ext_DataAdr[23]), .S0
       (reset), .Y (DataAdr[23]));
  MX2XL g1758__1881(.A (DataAdr_rv32[18]), .B (Ext_DataAdr[18]), .S0
       (reset), .Y (DataAdr[18]));
  MX2XL g1759__5115(.A (DataAdr_rv32[29]), .B (Ext_DataAdr[29]), .S0
       (reset), .Y (DataAdr[29]));
  MX2XL g1760__7482(.A (DataAdr_rv32[11]), .B (Ext_DataAdr[11]), .S0
       (reset), .Y (DataAdr[11]));
  MX2XL g1761__4733(.A (DataAdr_rv32[27]), .B (Ext_DataAdr[27]), .S0
       (reset), .Y (DataAdr[27]));
  NAND2BXL g1762__6161(.AN (MemWrite_rv32), .B (n_1), .Y (MemWrite));
  MX2XL g1763__9315(.A (DataAdr_rv32[1]), .B (Ext_DataAdr[1]), .S0
       (reset), .Y (DataAdr[1]));
  MX2XL g1764__9945(.A (DataAdr_rv32[10]), .B (Ext_DataAdr[10]), .S0
       (reset), .Y (DataAdr[10]));
  MX2XL g1765__2883(.A (DataAdr_rv32[12]), .B (Ext_DataAdr[12]), .S0
       (reset), .Y (DataAdr[12]));
  MX2XL g1766__2346(.A (DataAdr_rv32[24]), .B (Ext_DataAdr[24]), .S0
       (reset), .Y (DataAdr[24]));
  MX2XL g1767__1666(.A (DataAdr_rv32[2]), .B (Ext_DataAdr[2]), .S0
       (reset), .Y (DataAdr[2]));
  MX2XL g1768__7410(.A (DataAdr_rv32[0]), .B (Ext_DataAdr[0]), .S0
       (reset), .Y (DataAdr[0]));
  MX2XL g1769__6417(.A (DataAdr_rv32[13]), .B (Ext_DataAdr[13]), .S0
       (reset), .Y (DataAdr[13]));
  MX2XL g1770__5477(.A (DataAdr_rv32[3]), .B (Ext_DataAdr[3]), .S0
       (reset), .Y (DataAdr[3]));
  MX2XL g1771__2398(.A (DataAdr_rv32[20]), .B (Ext_DataAdr[20]), .S0
       (reset), .Y (DataAdr[20]));
  MX2XL g1772__5107(.A (DataAdr_rv32[31]), .B (Ext_DataAdr[31]), .S0
       (reset), .Y (DataAdr[31]));
  MX2XL g1773__6260(.A (DataAdr_rv32[4]), .B (Ext_DataAdr[4]), .S0
       (reset), .Y (DataAdr[4]));
  MX2XL g1774__4319(.A (DataAdr_rv32[14]), .B (Ext_DataAdr[14]), .S0
       (reset), .Y (DataAdr[14]));
  MX2XL g1775__8428(.A (DataAdr_rv32[25]), .B (Ext_DataAdr[25]), .S0
       (reset), .Y (DataAdr[25]));
  MX2XL g1776__5526(.A (DataAdr_rv32[5]), .B (Ext_DataAdr[5]), .S0
       (reset), .Y (DataAdr[5]));
  MX2XL g1777__6783(.A (DataAdr_rv32[21]), .B (Ext_DataAdr[21]), .S0
       (reset), .Y (DataAdr[21]));
  MX2XL g1778__3680(.A (DataAdr_rv32[15]), .B (Ext_DataAdr[15]), .S0
       (reset), .Y (DataAdr[15]));
  MX2XL g1779__1617(.A (DataAdr_rv32[6]), .B (Ext_DataAdr[6]), .S0
       (reset), .Y (DataAdr[6]));
  OR2X2 g1780__2802(.A (n_0), .B (n_2), .Y (n_1));
  INVX1 g1781(.A (reset), .Y (n_0));
endmodule

