
//input ports
add mapped point clk clk -type PI PI
add mapped point reset reset -type PI PI
add mapped point Ext_MemWrite Ext_MemWrite -type PI PI
add mapped point Ext_WriteData[31] Ext_WriteData[31] -type PI PI
add mapped point Ext_WriteData[30] Ext_WriteData[30] -type PI PI
add mapped point Ext_WriteData[29] Ext_WriteData[29] -type PI PI
add mapped point Ext_WriteData[28] Ext_WriteData[28] -type PI PI
add mapped point Ext_WriteData[27] Ext_WriteData[27] -type PI PI
add mapped point Ext_WriteData[26] Ext_WriteData[26] -type PI PI
add mapped point Ext_WriteData[25] Ext_WriteData[25] -type PI PI
add mapped point Ext_WriteData[24] Ext_WriteData[24] -type PI PI
add mapped point Ext_WriteData[23] Ext_WriteData[23] -type PI PI
add mapped point Ext_WriteData[22] Ext_WriteData[22] -type PI PI
add mapped point Ext_WriteData[21] Ext_WriteData[21] -type PI PI
add mapped point Ext_WriteData[20] Ext_WriteData[20] -type PI PI
add mapped point Ext_WriteData[19] Ext_WriteData[19] -type PI PI
add mapped point Ext_WriteData[18] Ext_WriteData[18] -type PI PI
add mapped point Ext_WriteData[17] Ext_WriteData[17] -type PI PI
add mapped point Ext_WriteData[16] Ext_WriteData[16] -type PI PI
add mapped point Ext_WriteData[15] Ext_WriteData[15] -type PI PI
add mapped point Ext_WriteData[14] Ext_WriteData[14] -type PI PI
add mapped point Ext_WriteData[13] Ext_WriteData[13] -type PI PI
add mapped point Ext_WriteData[12] Ext_WriteData[12] -type PI PI
add mapped point Ext_WriteData[11] Ext_WriteData[11] -type PI PI
add mapped point Ext_WriteData[10] Ext_WriteData[10] -type PI PI
add mapped point Ext_WriteData[9] Ext_WriteData[9] -type PI PI
add mapped point Ext_WriteData[8] Ext_WriteData[8] -type PI PI
add mapped point Ext_WriteData[7] Ext_WriteData[7] -type PI PI
add mapped point Ext_WriteData[6] Ext_WriteData[6] -type PI PI
add mapped point Ext_WriteData[5] Ext_WriteData[5] -type PI PI
add mapped point Ext_WriteData[4] Ext_WriteData[4] -type PI PI
add mapped point Ext_WriteData[3] Ext_WriteData[3] -type PI PI
add mapped point Ext_WriteData[2] Ext_WriteData[2] -type PI PI
add mapped point Ext_WriteData[1] Ext_WriteData[1] -type PI PI
add mapped point Ext_WriteData[0] Ext_WriteData[0] -type PI PI
add mapped point Ext_DataAdr[31] Ext_DataAdr[31] -type PI PI
add mapped point Ext_DataAdr[30] Ext_DataAdr[30] -type PI PI
add mapped point Ext_DataAdr[29] Ext_DataAdr[29] -type PI PI
add mapped point Ext_DataAdr[28] Ext_DataAdr[28] -type PI PI
add mapped point Ext_DataAdr[27] Ext_DataAdr[27] -type PI PI
add mapped point Ext_DataAdr[26] Ext_DataAdr[26] -type PI PI
add mapped point Ext_DataAdr[25] Ext_DataAdr[25] -type PI PI
add mapped point Ext_DataAdr[24] Ext_DataAdr[24] -type PI PI
add mapped point Ext_DataAdr[23] Ext_DataAdr[23] -type PI PI
add mapped point Ext_DataAdr[22] Ext_DataAdr[22] -type PI PI
add mapped point Ext_DataAdr[21] Ext_DataAdr[21] -type PI PI
add mapped point Ext_DataAdr[20] Ext_DataAdr[20] -type PI PI
add mapped point Ext_DataAdr[19] Ext_DataAdr[19] -type PI PI
add mapped point Ext_DataAdr[18] Ext_DataAdr[18] -type PI PI
add mapped point Ext_DataAdr[17] Ext_DataAdr[17] -type PI PI
add mapped point Ext_DataAdr[16] Ext_DataAdr[16] -type PI PI
add mapped point Ext_DataAdr[15] Ext_DataAdr[15] -type PI PI
add mapped point Ext_DataAdr[14] Ext_DataAdr[14] -type PI PI
add mapped point Ext_DataAdr[13] Ext_DataAdr[13] -type PI PI
add mapped point Ext_DataAdr[12] Ext_DataAdr[12] -type PI PI
add mapped point Ext_DataAdr[11] Ext_DataAdr[11] -type PI PI
add mapped point Ext_DataAdr[10] Ext_DataAdr[10] -type PI PI
add mapped point Ext_DataAdr[9] Ext_DataAdr[9] -type PI PI
add mapped point Ext_DataAdr[8] Ext_DataAdr[8] -type PI PI
add mapped point Ext_DataAdr[7] Ext_DataAdr[7] -type PI PI
add mapped point Ext_DataAdr[6] Ext_DataAdr[6] -type PI PI
add mapped point Ext_DataAdr[5] Ext_DataAdr[5] -type PI PI
add mapped point Ext_DataAdr[4] Ext_DataAdr[4] -type PI PI
add mapped point Ext_DataAdr[3] Ext_DataAdr[3] -type PI PI
add mapped point Ext_DataAdr[2] Ext_DataAdr[2] -type PI PI
add mapped point Ext_DataAdr[1] Ext_DataAdr[1] -type PI PI
add mapped point Ext_DataAdr[0] Ext_DataAdr[0] -type PI PI

//output ports
add mapped point MemWrite MemWrite -type PO PO
add mapped point WriteData[31] WriteData[31] -type PO PO
add mapped point WriteData[30] WriteData[30] -type PO PO
add mapped point WriteData[29] WriteData[29] -type PO PO
add mapped point WriteData[28] WriteData[28] -type PO PO
add mapped point WriteData[27] WriteData[27] -type PO PO
add mapped point WriteData[26] WriteData[26] -type PO PO
add mapped point WriteData[25] WriteData[25] -type PO PO
add mapped point WriteData[24] WriteData[24] -type PO PO
add mapped point WriteData[23] WriteData[23] -type PO PO
add mapped point WriteData[22] WriteData[22] -type PO PO
add mapped point WriteData[21] WriteData[21] -type PO PO
add mapped point WriteData[20] WriteData[20] -type PO PO
add mapped point WriteData[19] WriteData[19] -type PO PO
add mapped point WriteData[18] WriteData[18] -type PO PO
add mapped point WriteData[17] WriteData[17] -type PO PO
add mapped point WriteData[16] WriteData[16] -type PO PO
add mapped point WriteData[15] WriteData[15] -type PO PO
add mapped point WriteData[14] WriteData[14] -type PO PO
add mapped point WriteData[13] WriteData[13] -type PO PO
add mapped point WriteData[12] WriteData[12] -type PO PO
add mapped point WriteData[11] WriteData[11] -type PO PO
add mapped point WriteData[10] WriteData[10] -type PO PO
add mapped point WriteData[9] WriteData[9] -type PO PO
add mapped point WriteData[8] WriteData[8] -type PO PO
add mapped point WriteData[7] WriteData[7] -type PO PO
add mapped point WriteData[6] WriteData[6] -type PO PO
add mapped point WriteData[5] WriteData[5] -type PO PO
add mapped point WriteData[4] WriteData[4] -type PO PO
add mapped point WriteData[3] WriteData[3] -type PO PO
add mapped point WriteData[2] WriteData[2] -type PO PO
add mapped point WriteData[1] WriteData[1] -type PO PO
add mapped point WriteData[0] WriteData[0] -type PO PO
add mapped point DataAdr[31] DataAdr[31] -type PO PO
add mapped point DataAdr[30] DataAdr[30] -type PO PO
add mapped point DataAdr[29] DataAdr[29] -type PO PO
add mapped point DataAdr[28] DataAdr[28] -type PO PO
add mapped point DataAdr[27] DataAdr[27] -type PO PO
add mapped point DataAdr[26] DataAdr[26] -type PO PO
add mapped point DataAdr[25] DataAdr[25] -type PO PO
add mapped point DataAdr[24] DataAdr[24] -type PO PO
add mapped point DataAdr[23] DataAdr[23] -type PO PO
add mapped point DataAdr[22] DataAdr[22] -type PO PO
add mapped point DataAdr[21] DataAdr[21] -type PO PO
add mapped point DataAdr[20] DataAdr[20] -type PO PO
add mapped point DataAdr[19] DataAdr[19] -type PO PO
add mapped point DataAdr[18] DataAdr[18] -type PO PO
add mapped point DataAdr[17] DataAdr[17] -type PO PO
add mapped point DataAdr[16] DataAdr[16] -type PO PO
add mapped point DataAdr[15] DataAdr[15] -type PO PO
add mapped point DataAdr[14] DataAdr[14] -type PO PO
add mapped point DataAdr[13] DataAdr[13] -type PO PO
add mapped point DataAdr[12] DataAdr[12] -type PO PO
add mapped point DataAdr[11] DataAdr[11] -type PO PO
add mapped point DataAdr[10] DataAdr[10] -type PO PO
add mapped point DataAdr[9] DataAdr[9] -type PO PO
add mapped point DataAdr[8] DataAdr[8] -type PO PO
add mapped point DataAdr[7] DataAdr[7] -type PO PO
add mapped point DataAdr[6] DataAdr[6] -type PO PO
add mapped point DataAdr[5] DataAdr[5] -type PO PO
add mapped point DataAdr[4] DataAdr[4] -type PO PO
add mapped point DataAdr[3] DataAdr[3] -type PO PO
add mapped point DataAdr[2] DataAdr[2] -type PO PO
add mapped point DataAdr[1] DataAdr[1] -type PO PO
add mapped point DataAdr[0] DataAdr[0] -type PO PO
add mapped point ReadData[31] ReadData[31] -type PO PO
add mapped point ReadData[30] ReadData[30] -type PO PO
add mapped point ReadData[29] ReadData[29] -type PO PO
add mapped point ReadData[28] ReadData[28] -type PO PO
add mapped point ReadData[27] ReadData[27] -type PO PO
add mapped point ReadData[26] ReadData[26] -type PO PO
add mapped point ReadData[25] ReadData[25] -type PO PO
add mapped point ReadData[24] ReadData[24] -type PO PO
add mapped point ReadData[23] ReadData[23] -type PO PO
add mapped point ReadData[22] ReadData[22] -type PO PO
add mapped point ReadData[21] ReadData[21] -type PO PO
add mapped point ReadData[20] ReadData[20] -type PO PO
add mapped point ReadData[19] ReadData[19] -type PO PO
add mapped point ReadData[18] ReadData[18] -type PO PO
add mapped point ReadData[17] ReadData[17] -type PO PO
add mapped point ReadData[16] ReadData[16] -type PO PO
add mapped point ReadData[15] ReadData[15] -type PO PO
add mapped point ReadData[14] ReadData[14] -type PO PO
add mapped point ReadData[13] ReadData[13] -type PO PO
add mapped point ReadData[12] ReadData[12] -type PO PO
add mapped point ReadData[11] ReadData[11] -type PO PO
add mapped point ReadData[10] ReadData[10] -type PO PO
add mapped point ReadData[9] ReadData[9] -type PO PO
add mapped point ReadData[8] ReadData[8] -type PO PO
add mapped point ReadData[7] ReadData[7] -type PO PO
add mapped point ReadData[6] ReadData[6] -type PO PO
add mapped point ReadData[5] ReadData[5] -type PO PO
add mapped point ReadData[4] ReadData[4] -type PO PO
add mapped point ReadData[3] ReadData[3] -type PO PO
add mapped point ReadData[2] ReadData[2] -type PO PO
add mapped point ReadData[1] ReadData[1] -type PO PO
add mapped point ReadData[0] ReadData[0] -type PO PO
add mapped point PC[31] PC[31] -type PO PO
add mapped point PC[30] PC[30] -type PO PO
add mapped point PC[29] PC[29] -type PO PO
add mapped point PC[28] PC[28] -type PO PO
add mapped point PC[27] PC[27] -type PO PO
add mapped point PC[26] PC[26] -type PO PO
add mapped point PC[25] PC[25] -type PO PO
add mapped point PC[24] PC[24] -type PO PO
add mapped point PC[23] PC[23] -type PO PO
add mapped point PC[22] PC[22] -type PO PO
add mapped point PC[21] PC[21] -type PO PO
add mapped point PC[20] PC[20] -type PO PO
add mapped point PC[19] PC[19] -type PO PO
add mapped point PC[18] PC[18] -type PO PO
add mapped point PC[17] PC[17] -type PO PO
add mapped point PC[16] PC[16] -type PO PO
add mapped point PC[15] PC[15] -type PO PO
add mapped point PC[14] PC[14] -type PO PO
add mapped point PC[13] PC[13] -type PO PO
add mapped point PC[12] PC[12] -type PO PO
add mapped point PC[11] PC[11] -type PO PO
add mapped point PC[10] PC[10] -type PO PO
add mapped point PC[9] PC[9] -type PO PO
add mapped point PC[8] PC[8] -type PO PO
add mapped point PC[7] PC[7] -type PO PO
add mapped point PC[6] PC[6] -type PO PO
add mapped point PC[5] PC[5] -type PO PO
add mapped point PC[4] PC[4] -type PO PO
add mapped point PC[3] PC[3] -type PO PO
add mapped point PC[2] PC[2] -type PO PO
add mapped point PC[1] PC[1] -type PO PO
add mapped point PC[0] PC[0] -type PO PO
add mapped point Result[31] Result[31] -type PO PO
add mapped point Result[30] Result[30] -type PO PO
add mapped point Result[29] Result[29] -type PO PO
add mapped point Result[28] Result[28] -type PO PO
add mapped point Result[27] Result[27] -type PO PO
add mapped point Result[26] Result[26] -type PO PO
add mapped point Result[25] Result[25] -type PO PO
add mapped point Result[24] Result[24] -type PO PO
add mapped point Result[23] Result[23] -type PO PO
add mapped point Result[22] Result[22] -type PO PO
add mapped point Result[21] Result[21] -type PO PO
add mapped point Result[20] Result[20] -type PO PO
add mapped point Result[19] Result[19] -type PO PO
add mapped point Result[18] Result[18] -type PO PO
add mapped point Result[17] Result[17] -type PO PO
add mapped point Result[16] Result[16] -type PO PO
add mapped point Result[15] Result[15] -type PO PO
add mapped point Result[14] Result[14] -type PO PO
add mapped point Result[13] Result[13] -type PO PO
add mapped point Result[12] Result[12] -type PO PO
add mapped point Result[11] Result[11] -type PO PO
add mapped point Result[10] Result[10] -type PO PO
add mapped point Result[9] Result[9] -type PO PO
add mapped point Result[8] Result[8] -type PO PO
add mapped point Result[7] Result[7] -type PO PO
add mapped point Result[6] Result[6] -type PO PO
add mapped point Result[5] Result[5] -type PO PO
add mapped point Result[4] Result[4] -type PO PO
add mapped point Result[3] Result[3] -type PO PO
add mapped point Result[2] Result[2] -type PO PO
add mapped point Result[1] Result[1] -type PO PO
add mapped point Result[0] Result[0] -type PO PO

//inout ports




//Sequential Pins



//Black Boxes



//Empty Modules as Blackboxes
add mapped point datamem datamem -type BBOX BBOX
add mapped point instrmem instrmem -type BBOX BBOX
add mapped point rvcpu rvcpu -type BBOX BBOX
